#!/bin/bash
# GitHub Push Instructions for IDQL Repository

echo "========================================="
echo "IDQL Repository - Ready to Push to GitHub"
echo "========================================="
echo ""
echo "Repository prepared at: /home/claude/IDQL"
echo "Target: https://github.com/PeymanAudioML/IDQL"
echo ""
echo "To push this repository to GitHub, follow these steps:"
echo ""
echo "1. First, make sure you have GitHub CLI or Git configured with your credentials"
echo ""
echo "2. If the repository doesn't exist on GitHub yet, create it:"
echo "   gh repo create PeymanAudioML/IDQL --public --description 'PyTorch implementation of IDQL (Implicit Diffusion Q-Learning)'"
echo ""
echo "3. Push the repository:"
echo "   cd /home/claude/IDQL"
echo "   git push -u origin main"
echo ""
echo "Alternative: If you want to clone this to your local machine first:"
echo "   tar -czf idql-repo.tar.gz -C /home/claude IDQL"
echo "   # Download the tar file"
echo "   # Extract locally: tar -xzf idql-repo.tar.gz"
echo "   # cd IDQL"
echo "   # git remote set-url origin https://github.com/PeymanAudioML/IDQL.git"
echo "   # git push -u origin main"
echo ""
echo "Repository contents:"
ls -la /home/claude/IDQL/
echo ""
echo "Git status:"
cd /home/claude/IDQL && git status
echo ""
echo "Git log:"
cd /home/claude/IDQL && git log --oneline
